name       : audacity
version    : 2.2.0
release    : 8
source     :
    - https://github.com/audacity/audacity/archive/Audacity-2.2.0.tar.gz : 3e4b6861f45885e4c90db62eb479cab2a9361e1ebb0c567bf8362a2b17c9b727
license    :
    - GPL-2.0 # Source
    - CC-3.0 # Documentation
component  : multimedia.audio
summary    : A Free, Cross-Platform Digital Audio Editor
description: |
    A Free, Cross-Platform Digital Audio Editor
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(expat)
    - pkgconfig(flac)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(lilv-0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(soundtouch)
    - pkgconfig(soxr)
    - pkgconfig(suil-0)
    - pkgconfig(twolame)
    - pkgconfig(vamp)
    - pkgconfig(vorbis)
    - lame-devel
    - libid3tag-devel
    - libmad-devel
    - wxwidgets-devel
setup      : |
    %configure --disable-dynamic-loading --disable-static
build      : |
    %make
install    : |
    %make_install
