name       : audacity
version    : 2.1.2
release    : 3
source     :
    - https://github.com/audacity/audacity/archive/Audacity-2.1.2.tar.gz : 90007b50cdc3885607b1afef2f158777a61c1658e869a88ec4d98c59c133f9bd
license    :
    - GPL-2.0 # Source
    - CC-3.0 # Documentation
component  : multimedia.audio
summary    : A Free, Cross-Platform Digital Audio Editor
description: |
    A Free, Cross-Platform Digital Audio Editor
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(expat)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(soxr)
    - pkgconfig(twolame)
    - pkgconfig(vamp)
    - pkgconfig(vorbis)
    - lame-devel
    - libid3tag-devel
    - wxwidgets-devel
setup      : |
    %patch -p1 < $pkgfiles/la.patch
    %configure --disable-dynamic-loading --disable-static --without-libflac
build      : |
    %make
install    : |
    %make_install
