name       : audacity
version    : 2.3.2
release    : 20
source     :
    - https://github.com/audacity/audacity/archive/Audacity-2.3.2.tar.gz : cc477a71ff5571c72887a7a155365b07a1a50bcea1abf490a4de7b884376c731
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : multimedia.audio
summary    : A Free, Cross-Platform Digital Audio Editor
description: |
    Audacity is free, open source, cross-platform audio software for multi-track recording and editing.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(expat)
    - pkgconfig(flac)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(id3tag)
    - pkgconfig(libavcodec)
    - pkgconfig(lilv-0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(soundtouch)
    - pkgconfig(soxr)
    - pkgconfig(suil-0)
    - pkgconfig(twolame)
    - pkgconfig(vamp)
    - pkgconfig(vorbis)
    - lame-devel
    - libmad-devel
    - wxwidgets-devel
setup      : |
    %configure --disable-dynamic-loading --disable-static
build      : |
    %make
install    : |
    %make_install
