name       : audacity
version    : 2.2.2
release    : 15
source     :
    - https://github.com/audacity/audacity/archive/Audacity-2.2.2.tar.gz : 759e8efd5e4ff6cc2fdd31b36bc631307330c1a6e2d3426e3f1d46ebcf8907a3
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : multimedia.audio
summary    : A Free, Cross-Platform Digital Audio Editor
description: |
    Audacity is free, open source, cross-platform audio software for multi-track recording and editing.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(expat)
    - pkgconfig(flac)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(id3tag)
    - pkgconfig(libavcodec)
    - pkgconfig(lilv-0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(soundtouch)
    - pkgconfig(soxr)
    - pkgconfig(suil-0)
    - pkgconfig(twolame)
    - pkgconfig(vamp)
    - pkgconfig(vorbis)
    - lame-devel
    - libmad-devel
    - wxwidgets-devel
setup      : |
    %configure --disable-dynamic-loading --disable-static
build      : |
    %make
install    : |
    %make_install
