name       : audacity
version    : 2.2.1
release    : 10
source     :
    - https://github.com/audacity/audacity/archive/Audacity-2.2.1.tar.gz : ff346e7a68a57a05089813efd78a81439f5419d211f80bb472c9d94c16ca05d8
license    :
    - GPL-2.0
    - CC-3.0
component  : multimedia.audio
summary    : A Free, Cross-Platform Digital Audio Editor
description: |
    Audacity is free, open source, cross-platform audio software for multi-track recording and editing.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(expat)
    - pkgconfig(flac)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libavcodec)
    - pkgconfig(lilv-0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(soundtouch)
    - pkgconfig(soxr)
    - pkgconfig(suil-0)
    - pkgconfig(twolame)
    - pkgconfig(vamp)
    - pkgconfig(vorbis)
    - lame-devel
    - libid3tag-devel
    - libmad-devel
    - wxwidgets-devel
setup      : |
    %configure --disable-dynamic-loading --disable-static
build      : |
    %make
install    : |
    %make_install
