name       : audacity
version    : 2.3.3
release    : 22
source     :
    - https://github.com/audacity/audacity/archive/Audacity-2.3.3.tar.gz : 404e6c49693dedc94212fc5525974058d848536025e19da31359ae02babe8bd7
license    :
    - CC-BY-SA-3.0
    - GPL-2.0-or-later
component  : multimedia.audio
summary    : A Free, Cross-Platform Digital Audio Editor
description: |
    Audacity is free, open source, cross-platform audio software for multi-track recording and editing.
builddeps  :
    - pkgconfig(alsa)
    - pkgconfig(expat)
    - pkgconfig(flac)
    - pkgconfig(gstreamer-base-1.0)
    - pkgconfig(gtk+-2.0)
    - pkgconfig(id3tag)
    - pkgconfig(libavcodec)
    - pkgconfig(lilv-0)
    - pkgconfig(portaudio-2.0)
    - pkgconfig(samplerate)
    - pkgconfig(sndfile)
    - pkgconfig(soundtouch)
    - pkgconfig(soxr)
    - pkgconfig(suil-0)
    - pkgconfig(twolame)
    - pkgconfig(vamp)
    - pkgconfig(vorbis)
    - lame-devel
    - libmad-devel
    - wxwidgets-devel
rundeps    :
    - alsa-plugins
setup      : |
    %configure --disable-dynamic-loading --disable-static
build      : |
    %make
install    : |
    %make_install
